### ISSUE TITLE
new block found pool

### ISSUE THREAD

**Issue by Simkas45** [RafaMunoz/bot-openethereumpool#2]
Please, could you add a notice when you find a new block?

**Comment by RafaMunoz** [comment]
> Please, could you add a notice when you find a new block?

Hi @Simkas45 , if you are interested I will try to develop it soon.

**Comment by Simkas45** [comment]
I really liked your bot, could you still add permanent buttons to the bot?
your work is just wonderful!

**Comment by RafaMunoz** [comment]
> I really liked your bot, could you still add permanent buttons to the bot?
> your work is just wonderful!

Thanks a lot!  I will work on the keyboard after the notifications of new blocks.

**Comment by Simkas45** [comment]
please make a notice as soon as possible on newly found blocks, a very necessary thing!

**Comment by Simkas45** [comment]
my old development from a friend can help you with something

`#!/usr/bin/env python3
from bot.models import User, minerstate
from config import aiohttp_session, PROXY_URL, TOKEN
import time
import configparser
import asyncio

"""
FOR USE:

chmod u+x /root/btc-bot/notify_scheduler.py
crontab -e, nano
*/1 * * * * /root/btc-bot/notify_scheduler.py

"""

blocks = configparser.ConfigParser()
blocks.read("blocks.ini")


async def get_miner_stats(wallet):
    async with aiohttp_session.get(
        f"http://example.com/api/accounts/{wallet}"
    ) as response:
        r = await response.json()
        state = minerstate.State(
            r.get("currentHashrate"),
            r["stats"].get("blocksFound", 0),
            r["stats"]["balance"],
            r["paymentsTotal"],
            r["stats"]["paid"],
            r["workersOnline"],
            r["workersOffline"],
        )
        return state.to_string()


async def check_block():
    async with aiohttp_session.get("http://example.com/api/stats") as response:
        r = await response.json()
        if r["candidatesTotal"] > blocks["candidatesTotal"]:
            blocks["candidatesTotal"] += 1
            with open("blocks.ini", "w") as configfile:
                blocks.write(configfile)
            return True


async def send_notify(uid, wallet, lang):
    response = await get_miner_stats(wallet)
    notify = "NEW NOTIFY!" if lang == "en" else "НОВОЕ УВЕДОМЛЕНИЕ!"
    response = "{notify} \n\n".format(notify=notify) + response
    try:
        async with aiohttp_session.post(
            f"https://api.telegram.org/bot{TOKEN}/sendMessage?chat_id={uid}&text={response}",
            proxy=PROXY_URL,
        ) as response:
            if response.status == 200:
                await User.edit_tosend(uid)

        if await check_block():

            response = "PULL FIND BLOCK!" if lang == "en" else "Пулл нашёл новый блок!"
            async with aiohttp_session.post(
                f"https://api.telegram.org/bot{TOKEN}/sendMessage?chat_id={uid}&text={response}",
                proxy=PROXY_URL,
            ) as response:
                pass
    except:
        pass


async def add_schedules():
    users = await User.get_notify_list()
    for user in users:
        if time.time() > user["to_send"]:
            notify_time = user["notify_time"]
            uid = user["uid"]
            wallet = user["wallet_address"]
            lang = user["lang"]
            await send_notify(uid, wallet, lang)


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(add_schedules())
`

**Comment by RafaMunoz** [comment]
Thanks for the help but that script is not valid for my bot.  Currently I have it developed but I am doing tests with a Pool and that takes time since a new block is not found very often.

**Comment by Simkas45** [comment]
my stats pool http://45.147.199.232/api/stats
no public pool, only solo mining, payout off !

**Comment by RafaMunoz** [comment]
New Block notification is already implemented, I can hardly test it. If you find any bug notify me.

**Comment by Simkas45** [comment]
my error start script 
http://icecream.me/uploads/e6a9187b9bb14f2df194cf3d4239e186.png

**Comment by Simkas45** [comment]
i am sorry, my config no new line

**Comment by Simkas45** [comment]
script checkNewblock add to crontab?

**Comment by Simkas45** [comment]
general script error
http://icecream.me/7809a149193da022380f821db742cfd1

**Comment by Simkas45** [comment]
new errors when viewing statistics of your address the script closes, then the notification_newblock parameter does not change to true or false through the bot

**Comment by RafaMunoz** [comment]
Correctly the statistics were wrong and are already corrected.
The error you comment on notifications I do not see, ami works correctly for me.

**Comment by Simkas45** [comment]
my pool found a new block but there was no notification in the bot

**Comment by Simkas45** [comment]
[http://icecream.me/uploads/21588f7b0e3b126ba6e28b4b185d5975.png](url)

**Comment by Simkas45** [comment]
http://icecream.me/uploads/c501baf82b1c5924307e3787751c118d.png

**Comment by Simkas45** [comment]
i am sorry i fixed error database.
I now have a new error, there are no buttons in the bot to select my address which statistics to show

**Comment by Simkas45** [comment]
[http://icecream.me/uploads/2b5668343d4ba5e631e2ef54f720002e.png](url)
[http://icecream.me/uploads/ecab9a0c0fadfd249bba1921837a09c5.png](url)

**Comment by RafaMunoz** [comment]
The problem is that you have used the latest version of mongodb and the bot is not compatible. I am working to solve it.

**Comment by Simkas45** [comment]
uncle block not notifer ?

**Comment by Simkas45** [comment]
i found uncle block etc, bot not send my notify

**Comment by Simkas45** [comment]
`2020-05-08 22:10:01,687 - checkWorkers - INFO - --- Start CheckWorkers ---
2020-05-08 22:10:01,688 - checkWorkers - INFO - --- Start CheckNewBlock ---
2020-05-08 22:10:01,695 - checkWorkers - DEBUG - Search addresses notifications=True
2020-05-08 22:10:01,709 - checkWorkers - DEBUG - idUser: 362551871, address: 0xa4d4589a1d6e273ca4bc018efc4b691f396e6490
2020-05-08 22:10:01,716 - checkWorkers - DEBUG - Search block in db: {'height': 10346285, 'timestamp': 1588964711, 'difficulty': 120293333747905, 'shares': 23298000000000, 'uncle': True, 'uncleHeight': 10346282, 'orphan': False, 'hash': '0x350795da20c09e94e9a2dc9db2ed54aa3097fb0a1e51275ece8b0deb49217ce6', 'login': '0xa4d4589a1d6e273ca4bc018efc4b691f396e6490', 'reward': '100000000000000000'}
2020-05-08 22:10:01,762 - checkWorkers - DEBUG - Status workers for address: 0xa4d4589a1d6e273ca4bc018efc4b691f396e6490 {'10413': False, '10601P': False, '10602D': False, '10801': False, 'P1': False, 'P2': False, 'P3': False, 'P4': False, 'P5': False, 'P6': False, 'P7': False, 'R1': False, 'R10D': False, 'R11D': False, 'R2': False, 'R3': False, 'R4': False, 'R5M': False, 'R6': False, 'R7': False, 'R8D': False}
2020-05-08 22:10:01,767 - checkWorkers - DEBUG - Update status workers for 0xa4d4589a1d6e273ca4bc018efc4b691f396e6490
`

**Comment by Simkas45** [comment]
2020-05-08 22:10:01,687 - checkWorkers - INFO - --- Start CheckWorkers ---
2020-05-08 22:10:01,688 - checkWorkers - INFO - --- Start CheckNewBlock ---
2020-05-08 22:10:01,695 - checkWorkers - DEBUG - Search addresses notifications=True
2020-05-08 22:10:01,709 - checkWorkers - DEBUG - idUser: 362551871, address: 0xa4d4589a1d6e273ca4bc018efc4b691f396e6490
2020-05-08 22:10:01,716 - checkWorkers - DEBUG - Search block in db: {'height': 10346285, 'timestamp': 1588964711, 'difficulty': 120293333747905, 'shares': 23298000000000, 'uncle': True, 'uncleHeight': 10346282, 'orphan': False, 'hash': '0x350795da20c09e94e9a2dc9db2ed54aa3097fb0a1e51275ece8b0deb49217ce6', 'login': '0xa4d4589a1d6e273ca4bc018efc4b691f396e6490', 'reward': '100000000000000000'}
2020-05-08 22:10:01,762 - checkWorkers - DEBUG - Status workers for address: 0xa4d4589a1d6e273ca4bc018efc4b691f396e6490 {'10413': False, '10601P': False, '10602D': False, '10801': False, 'P1': False, 'P2': False, 'P3': False, 'P4': False, 'P5': False, 'P6': False, 'P7': False, 'R1': False, 'R10D': False, 'R11D': False, 'R2': False, 'R3': False, 'R4': False, 'R5M': False, 'R6': False, 'R7': False, 'R8D': False}
2020-05-08 22:10:01,767 - checkWorkers - DEBUG - Update status workers for 0xa4d4589a1d6e273ca4bc018efc4b691f396e6490

**Comment by Simkas45** [comment]
[http://icecream.me/uploads/fbd132f191e32ec2f32ea625dee0b98a.png](url)

**Comment by RafaMunoz** [comment]
Ya es compatible con la ultima version de mongodb, aunque todavia tengo que hacer correcciones ya puedes probarlo

Por favor redeploy el contenedor y ejecuta /start en el bot

**Comment by RafaMunoz** [comment]
It is already compatible with the latest version of mongodb, although I still have to make corrections you can try it

Please redeploy the container and run / start on the bot

**Comment by Simkas45** [comment]
Uncle block notifies the bot or not? for some reason I didn’t have a notice now, what is the reason?

**Comment by RafaMunoz** [comment]
I am consulting the statistics of your pool and the last time a block was found is at date: Friday, 8 May 2020 19:05:11
At that time the database was not working for that reason it has not notified.

**Comment by Simkas45** [comment]
launched the database turned on all notifications, waiting for a new block

**Comment by Simkas45** [comment]
new block found, bot notifer not send

**Comment by Simkas45** [comment]
crontab -e
*/1 * * * * /usr/bin/python3.7 /root/bot-openethereumpool/openethereumpool/checkNewBlock.py

**Comment by Simkas45** [comment]
[http://icecream.me/uploads/dfffb831bd59591a030b05a388aa2531.png](url)
[http://icecream.me/uploads/3c5f9adb93caffd059d1c3ae4bf242b2.png](url)

**Comment by Simkas45** [comment]
[http://icecream.me/uploads/636eaa54dc6b9ba99bb1850f013bdf96.png](url)

**Comment by Simkas45** [comment]
the block moved from new immediately to mature

**Comment by Simkas45** [comment]
my pool found new block
bot not notifer please fix 
[http://icecream.me/uploads/95e967c5ebde51048043238c837bf18c.png](url)

**Comment by RafaMunoz** [comment]
the link to the images does not work. 
The bot is ready to announce the new block in the first minutes of life in the inmature state, this is approximately 30 minutes and is checked every minute. 
Please for a better management write the issue in 1 single line

**Comment by Simkas45** [comment]
Now my pool has found a block; all the files have been updated with me; the bot has not sent a notification
[http://45.147.199.232/api/blocks](url)

**Comment by Simkas45** [comment]
![ice_screenshot_20200509-124816](https://user-images.githubusercontent.com/43626253/81470436-6f621200-91f3-11ea-98c2-f1726b7eee5b.png)

**Comment by Simkas45** [comment]
![ice_screenshot_20200509-125048](https://user-images.githubusercontent.com/43626253/81470506-bf40d900-91f3-11ea-86fe-d8a1bbcf0c04.png)

**Comment by RafaMunoz** [comment]
I have been monitoring your pool and I see that this block goes directly from "candidate" to "matured" in 5 minutes without going through "inmatured". That's the problem

**Comment by Simkas45** [comment]
just make a notification about finding a new block, so that each new block the bot sends notifications, no matter whether the block is uncle or not, just about each notification block

**Comment by RafaMunoz** [comment]
I can't do that because there are other pools that want to know when he's uncle and when he's not.
I will modify the bot in the case of your pool that does not go through "immature" status.

**Comment by Simkas45** [comment]
It would be very good for each notification block to come

**Comment by RafaMunoz** [comment]
I have modified enough of the code to be compatible with your pool since the blocks you detect do not go through the immature state. Right now you should notify what the block hash is detected for.
I am monitoring your pool, if you want you can try to redeploy the bot or wait for it to warn you that it works

**Comment by Simkas45** [comment]
I updated the files, launched the bot, I'm waiting for a new block to check the bot, I will report the result! thank you very much !

**Comment by RafaMunoz** [comment]
With the latest version I have received notification pointing to your pool. 
Did you receive notification?

https://imgur.com/50RTgsy

**Comment by Simkas45** [comment]
Good news, block notify bos send message!

![ice_screenshot_20200510-033742](https://user-images.githubusercontent.com/43626253/81488298-b988d900-926f-11ea-8238-37edfd81772c.png)
 !!!
Thank you
